TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 10.0
  sim_time: 1.0
  pdist_scale: 1.0
  gdist_scale: 0.8
  occdist_scale: 0.01
  meter_scoring: true
  publish_cost_grid_pc: true
