map_type: costmap

obstacle_range: 5.0
raytrace_range: 10.0

transform_tolerance: 0.3

inflation_radius: 0.6

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /mybot/laser/scan, marking: true, clearing: true}
